Parameters:
  Name:
    Type: String
Resources:
  Repository:
    Type: "AWS::ECR::Repository"
    Properties:
      EmptyOnDelete: true
      RepositoryName: !Ref Name
      ImageTagMutability: "IMMUTABLE"
Outputs:
  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri