region := env("AWS_REGION", "eu-west-1")

export AWS_REGION := region
export AWS_PAGER := ""

tf-apply:
    tofu init
    tofu apply -auto-approve -var "region={{region}}"

tf-destroy:
    tofu destroy -auto-approve -var "region={{region}}"

tf-fmt:
    tofu fmt -recursive .

invalidate-cache:
    #!/bin/bash -e
    id=$(tofu output -raw distribution_id)
    aws cloudfront create-invalidation \
        --distribution-id "$id" \
        --paths "/*"